### ISSUE TITLE
Add support for known TMOGs

### ISSUE THREAD

**Issue by claytonkimber** [Baganator/Syndicator#10]
**Is your feature request related to a problem? Please describe.**
No support for already known appearances to use for filtering out things that I can mail or sell

**Describe the solution you'd like**
Support for equipment items that have already been learned for appearances

**Describe alternatives you've considered**
Currently use ATT

**Additional context**

**Comment by plusmouse** [comment]
Added in the latest alpha:
[Syndicator-62-6-g3e598bc.zip](https://github.com/user-attachments/files/15848689/Syndicator-62-6-g3e598bc.zip)
