### ISSUE TITLE
AH pattern tooltip vs. crafted item tooltip

### ISSUE THREAD

**Issue by tflo** [Baganator/Syndicator#11]
It seems in most AH views Syndicator is displaying tooltip info for the crafted item, instead of the pattern. Example:

<details>
<summary>(1) Tooltip of the pattern on the AH</summary>
<img width="457" alt="image" src="https://github.com/Baganator/Syndicator/assets/1410282/d535f2fc-c3c8-40b6-8245-755c1009a3a6">

</details> 

<details>
<summary>(2) Tooltip of the pattern from the cached bag view</summary>
<img width="450" alt="image" src="https://github.com/Baganator/Syndicator/assets/1410282/88430c63-4484-4634-a559-a823b3ac9c43">

</details> 

<details>
<summary>(3) Tooltip of the crafted item on the AH</summary>
<img width="511" alt="image" src="https://github.com/Baganator/Syndicator/assets/1410282/0d464a2e-b12c-4532-8521-109c022df7d0">

</details> 

The problem lies in the first screenshot ((1) Tooltip of the pattern on the AH):

Syndicator is not displaying the one rank 3 pattern that I have in the bags of the tailor alt (as correctly displayed in (2)). Since the Oribos tooltip (the two separated price lines just above the TSM tooltip) is erroneously displaying the price of the crafted item, _I assume_ Syndicator is doing the same, hence no inventory record displayed.

TSM (inventory/prices), Auctionator (prices) and ATT (item/spell ID) are correctly showing the tooltip info for the pattern.

It seems this problem concerns all AH views (including Collectionator), _with one exception:_ In the final Buy listing (where I can click the Buyout button), Syndicator's inventory entry is there, and also Oribos correctly displays the price for the pattern.

So I guess something is a bit messy with the underlaying tooltip infos of the different AH views. However, the Auctionator/TSM/ATT tooltips manage to distinguish correctly between pattern and crafted item, and it would be great if Syndicator could do too.

It happened a few weeks ago that I bought a rank 3 recipe via Collectionator, where afterwards it turned out that I had it already in the bank of an alt, but back then I didn't know why this happened (I thought I had missed the inventory tooltip).

**Comment by plusmouse** [comment]
Fixed. This is a Blizzard bug, they return the crafted item by default as the tooltip's item info, so I've been fixing this on a case-by-case basis to get it working properly.

**Comment by tflo** [comment]
Works great now, thanks!
