### ISSUE TITLE
Error at every login on Era / Synticator-58-classic

### ISSUE THREAD

**Issue by Angerreign** [Baganator/Syndicator#12]
## Brief Description of Bug

Happens at every login after updating addon to latest version.

## Steps to Reproduce

At every loggin.

## Loaded Addons
AdvancedInterfaceOptions: disabled
Atlas: enabled
Atlas_Battlegrounds: enabled
Atlas_ClassicWoW: enabled
Atlas_DungeonLocs: enabled
Atlas_Transportation: enabled
AtlasLootClassic_Options: enabled
AtlasLootClassic_Collections: enabled
AtlasLootClassic_Crafting: enabled
AtlasLootClassic_DungeonsAndRaids: enabled
AtlasLootClassic_Factions: enabled
AtlasLootClassic_PvP: enabled
AtlasLootClassic: enabled
AtlasLootClassic_Data: enabled
ATT-Classic: disabled
Attune: enabled
Auctionator: enabled
BadBoy: enabled
BadBoy_CCleaner: enabled
BadBoy_Guilded: disabled
BadBoy_History: enabled
BadBoy_Ignore: enabled
BadBoy_Levels: enabled
BasicChatMods: disabled
BetterAddonList: enabled
BigDebuffs: enabled
!BugGrabber: enabled
BugSack: enabled
Capping: enabled
Capping_Options: enabled
ClassicAuraDurations: enabled
ClassicCastbars: disabled
ClassicCastbars_Options: disabled
ClassicHunterPetInfo: enabled
ClassicSpellActivations: enabled
Decursive: disabled
Details: enabled
Details_DataStorage: enabled
Details_Streamer: disabled
Details_TinyThreat: disabled
Diminish: enabled
Diminish_Options: enabled
ErrorMonster: enabled
ExtendedCharacterStats: disabled
GTFO: disabled
HandyNotes: enabled
HandyNotes_TravelGuide (Classic): enabled
HandyNotes_NPCs (Classic): enabled
HandyNotes_WorldMapButton: enabled
Leatrix_Maps: enabled
Leatrix_Plus: enabled
LFGBulletinBoard: disabled
LFG_MatchMaker: disabled
LibSharedMedia-3.0: enabled
LibClassicDurations: enabled
LinkSpellsClassic: enabled
ModernTargetFrame: enabled
Necrosis: disabled
NovaInstanceTracker: enabled
NovaWorldBuffs: enabled
OmniBar: disabled
OmniCC: enabled
OmniCC_Config: enabled
OmniCD: disabled
OPie: disabled
PixelPerfectAlign: enabled
Postal: enabled
Quartz: enabled
Questie: enabled
RareScanner: enabled
Spy: enabled
Talented: enabled
Talented_Data: enabled
Talented_Data_Export: enabled
Tamed: disabled
TidyPlates_ThreatPlates: enabled
ThreatClassic2: enabled
TomTom: enabled
WeaponSwingTimer: enabled
DBM-Core: enabled
DBM-GUI: enabled
DBM-StatusBarTimers: enabled
DBM-Azeroth: enabled
DBM-BWL: enabled
DBM-Party-Classic: enabled
DBM-MC: enabled
DBM-Naxx: enabled
DBM-Onyxia: enabled
DBM-AQ20: enabled
DBM-AQ40: enabled
DBM-VPVEM: enabled
DBM-ZG: enabled
TellMeWhen: disabled
TellMeWhen_Options: disabled
WhatsTraining: disabled
TrinketMenu: enabled
MoveAny: disabled
ImproveAny: disabled
ItemRack: enabled
ItemRackOptions: enabled
LoseControl: enabled
EasyFrames: enabled
sctd: enabled
sctd_options: enabled
sct_options: enabled
sct: enabled
SafeQueue: enabled
DBM-Party-Vanilla: enabled
Blizzard_CombatText: enabled
Drift: disabled
RCLootCouncil_Classic: disabled
TomCats: disabled
MacroManager: enabled
MacroManagerData: enabled
Parrot: enabled
Details_Compare2: enabled
Details_EncounterDetails: enabled
Details_RaidCheck: enabled
Details_Vanguard: enabled
LFG113: enabled
Auc-Advanced: enabled
Auc-Filter-Basic: enabled
Auc-ScanData: enabled
Auc-Stat-Histogram: enabled
Auc-Stat-iLevel: enabled
Auc-Stat-Purchased: enabled
Auc-Stat-Simple: enabled
Auc-Stat-StdDev: enabled
Auc-Util-FixAH: enabled
BeanCounter: enabled
Enchantrix: disabled
Enchantrix-Barker: disabled
Informant: enabled
SlideBar: enabled
Stubby: enabled
!Swatter: enabled
AAuctionatorTurkish: disabled
NugEnergy: disabled
MissingTradeSkillsList_TBC: disabled
MissingTradeSkillsList: enabled
GatherMate2: disabled
GatherMate2_Data: disabled
GatherMate2_HideNodes: disabled
GearMenu: disabled
DejaClassicStats: enabled
SinStats: disabled
unitscan: enabled
WeakAuras: disabled
WeakAurasArchive: disabled
WeakAurasModelPaths: disabled
WeakAurasOptions: disabled
WeakAurasTemplates: disabled
WeakAurasCompanion: enabled
TrackingEye: enabled
RangeDisplay: enabled
RangeDisplay_Options: enabled
TranqRotate: enabled
FloAspectBar: enabled
FloTotemBar: enabled
DBM-Raids-Vanilla: enabled
AllTheThings: enabled
Blizzard_CompactRaidFrames: enabled
MacroToolkit: enabled
MacroToolkitIcons: enabled
Prat-3.0: enabled
Prat-3.0_Libraries: enabled
SharedMedia_Noto: disabled
ClickedMedia: disabled
Clicked: disabled
InvenRaidFrames3: enabled
InvenRaidFrames3_Option: enabled
LossOfControlMessages: enabled
MuteSoundFile: enabled
MuteSoundFile_Options: enabled
Gargul: enabled
Deathlog: disabled
GSE: disabled
GSE_GUI: disabled
GSE_LDB: disabled
LiteButtonAuras: enabled
LittleWigs: enabled
LittleWigs_Classic: enabled
BigWigs: enabled
BigWigs_Classic: enabled
BigWigs_Core: enabled
BigWigs_Options: enabled
BigWigs_Plugins: enabled
DBM-SpellTimers: enabled
WhatsUp: disabled
NWTankAnnouncer: disabled
Buffalo: disabled
ClassicBestiary: enabled
EnhancedRaidFrames: disabled
MRT: disabled
RecipesCollector: disabled
Ranker: enabled
BagBrother: enabled
Bagnon: enabled
Bagnon_Config: enabled
Bagnon_ItemInfo: enabled
LootReserve: disabled
BasicMinimap: disabled
BasicMinimap_Options: disabled
BattlegroundTargets: disabled
ECDC: enabled
FiveSecondRule: enabled
StatWeightsClassic: disabled
DBM-Interrupts: disabled
GBankClassic: enabled
TipTac: enabled
TipTacItemRef: enabled
TipTacOptions: enabled
TipTacTalents: enabled
BetterFishing: enabled
CharacterStatsClassic: enabled
ExtraStats: enabled
Baganator: enabled
ArkInventory: enabled
ArkInventoryConfig: enabled
ArkInventoryRules: enabled
ArkInventorySearch: enabled
ArkInventoryRules_Example: disabled
BigWigs_Countdown_HeroesOfTheStorm: enabled
BigWigs_Countdown_Overwatch: enabled
BigWigs_Voice_KRgeelong: disabled
CraftInfoAnywhere: enabled
ClassicLootManager_Alerts: disabled
ClassicLootManager_Integrations: disabled
ClassicLootManager_Tracker: disabled
ClassicLootManager: disabled
WoWTR_Classic: disabled
BastionLoot: enabled
Skillet-Classic: disabled
RoutesGatherMate2IntegrationFix: disabled
RoutesImportExport: disabled
Routes: disabled
KeepTheHerbs: disabled
ClassicProfessionFilter: enabled
Pulse: disabled
Clique: disabled
Syndicator: enabled
GSE_Utils: disabled
NoteworthyII: disabled
CharacterNotes: enabled
unitscanData: enabled
LFGAnnouncements: enabled
Talented_SpecTabs: enabled
DBM-WorldEvents: enabled
Journalator: enabled
Journalator_Display: enabled
Journalator_OptionsUI: enabled
Journalator_Statistics: enabled
AskMrRobotClassic: enabled
LoggerHeadLite: disabled
AnglerAtlas: enabled
PartyPlanner: enabled
NeedToKnow: disabled
BuffomatClassic: disabled

## Back Trace (LUA Error Output)

3x Syndicator/Tracking/Main.lua:178: hooksecurefunc(): SetCurrencyByID is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Syndicator/Tracking/Main.lua"]:178: in function <Syndicator/Tracking/Main.lua:101>
[string "=[C]"]: in function `xpcall'
[string "@Syndicator/Tracking/Main.lua"]:236: in function `Initialize'
[string "@Syndicator/Core/Main.lua"]:10: in function `cb'
[string "@Syndicator/Core/Utilities.lua"]:12: in function <Syndicator/Core/Utilities.lua:9>

Locals:

**Comment by plusmouse** [comment]
Thanks for the bug report. Fixed in version 59, available from Curseforge and Wago shortly
[Syndicator-59-classic.zip](https://github.com/user-attachments/files/15804398/Syndicator-59-classic.zip)
