### ISSUE TITLE
Global search stopped working on one account

### ISSUE THREAD

**Issue by tflo** [Baganator/Syndicator#13]
`/bgrs`, and also the global search from the GUI, stopped working on my main account (i.e. no output to the chat console at all). Inventory tooltips are there and seem OK, bag/bank search in GUI still works. 

I’ve seen this the first time somewhere yesterday, and now today immediately at first login.

The weird stuff:

- Yesterday, I was able to get it to work again by exiting and restarting the game instance (reloading, relogging, or switching toons did not help, also rolling back some Syndicator versions (till 57) did not help).
- Today, the exit trick doesn't work, at least not after trying it 3 times.
- I don't have this problem (yet?) on my second (AH) account running in a second game instance on the same box.

Syndicator version is the same (60) on both accounts, both on Retail WoW.

Any idea?

**Comment by plusmouse** [comment]
Can you test this build?
[Syndicator-60-1-ge2a8c76.zip](https://github.com/user-attachments/files/15817459/Syndicator-60-1-ge2a8c76.zip)

**Comment by tflo** [comment]
Yeah, this version works again, so far (no exit, just reload) 😀

**Comment by plusmouse** [comment]
Great :)

**Comment by tflo** [comment]
So, the ATT timing stuff worked on my AH account but not on the main?

**Comment by plusmouse** [comment]
So its still broken?

**Comment by plusmouse** [comment]
That's OK then 🥳

**Comment by tflo** [comment]
Maybe related, since it's ATT, I had this error yesterday on the main account (never seen it before):

```denizenscript
6x AllTheThings/lib/Runner.lua:71: script ran too long
[string "@AllTheThings/lib/Runner.lua"]:71: in function <AllTheThings/lib/Runner.lua:66>

Locals:
ok = true
err = false
(*temporary) = false
(*temporary) = "AllTheThings/lib/Runner.lua:43: script ran too long"
(*temporary) = true
(*temporary) = false
(*temporary) = "script ran too long"
c_status = <function> defined =[C]:-1
StackCo = <no value>
SetStackCo = <function> defined @AllTheThings/lib/Runner.lua:34
RunningStack = nil
pcall = <function> defined =[C]:-1
c_resume = <function> defined =[C]:-1
PrintError = <function> defined @AllTheThings/lib/Runner.lua:16

```

**Comment by plusmouse** [comment]
Don't think its related. Someone on the ATT discord experienced it on the 6th of June though. (which is before I added the ATT data to Syndicator)

**Comment by tflo** [comment]
Thank you for the quick fix again!

**Comment by plusmouse** [comment]
Have you had an opportunity to make use of the ATT powered searches?
`currency` (items used at a vendor)
`objective` (items used to turn in a quest)
`att:Chip` (items used to acquire the Chip pet from a vendor, works for any item from a vendor in the ATT database)

**Comment by tflo** [comment]
See it in the release notes, but actually never tried.

I tried now your examples: The first two seem to work fine, but `att:Chip` doesn't return anything, though I have plenty of "Rock of Aegis" on various alts. (They are probably all in Void banks, is that the problem?)

**Comment by tflo** [comment]
A `/bgrs currency` _does_ return the "Rock of Aegis", but not the `/bgrs att:Chip`

**Comment by plusmouse** [comment]
Not sure why this is happening.

**Comment by tflo** [comment]
BTW, why does the search show so many separate instances of the same "Rock of Aegis" item? (see the screenshot that I've added to my last post)

**Comment by plusmouse** [comment]
Because the item link stored is slightly different for each one, usually with different modifiers/bonus ids

**Comment by tflo** [comment]
OK, I see. The majority differs in the last 2 or 3 digits (`item:198357::::::::14:264::::1:28:2\d{3}:::::`)
