### ISSUE TITLE
Currency for alts not updated on currency transfer in pre-patch

### ISSUE THREAD

**Issue by NoShotz** [Baganator/Syndicator#15]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When you transfer a currency from one character to another, it doesn't updated the currency for the character the currency was transferred from. In this case I transferred all my timewarped badges to my main character, but the value for the rest of my characters has not updated to reflect that.
![image](https://github.com/user-attachments/assets/2fa8d89e-eb89-46ee-b3ee-d83cea1fd62d)

## Steps to Reproduce

Transfer currency between characters

**Comment by plusmouse** [comment]
This feature is now in the latest alpha
