### ISSUE TITLE
Request: meta keyword for 'Can be equipped by my class'

### ISSUE THREAD

**Issue by Jahfry** [Baganator/Syndicator#18]
Request: add a keyword that means "equippable by my class". 

**Describe the solution you'd like**

This would be similar to the 'meta' keywords in #158. The idea in this case is to make Baganator more fluid between multiple characters. 

Assumption: I'm playing a Rogue. While it is currently possible to add "armor & leather" (or just "leather") to a category, that limits the category usefulness. 

Idea: add a keyword for 'equippable'. This would be evaluated when Addon loads and alias itself to whatever Armor and Weapon types the character can equip. 

This allows creating a generic "My Gear" category that only shows items this character can equip. Then a different category/section can handle all other types.

**Comment by plusmouse** [comment]
This is currently available as `#my class` a few releases ago.
