### ISSUE TITLE
Guild tagged with wrong server

### ISSUE THREAD

**Issue by ShetiPhian** [Baganator/Syndicator#20]
Not sure if its Syndicator storing the wrong data or a Baganator display issue.

Guilds where made on their server, has members from that server and the armory shows the correct server.
But their names are tagged with the wrong server.

Moonrunner appears as Trollbane
Skywall appears as Silvermoon
Steamwheedle Cartel appears as KirinTor
Windrunner appears as Suramar

Seems to be grabbing one from the connected servers list, maybe the first entry / primary server.

_Include the steps I would need to follow to reproduce the bug._
Hover over item that is in a guild bank

_Include a list of addons you were running at the time this bug occurred._
Many; 
Only Syndicator for data syncing, and Baganator for inventory.
I'll provide a full list if needed.

_You can get this through the use of !BugGrabber and BugSack addons._
No LUA errors, just a graphical display one.

**Comment by plusmouse** [comment]
Thanks for the bug report. This is now fixed in the latest alpha.
