### ISSUE TITLE
Show Complete List and Location Info in Tooltip

### ISSUE THREAD

**Issue by wheatbread** [Baganator/Syndicator#21]
**Is your feature request related to a problem? Please describe.**
Currently, when mousing over an item, it shows me an incomplete list of the characters who have it, says that it's equipped somewhere, and then trails off with an ellipsis.

![image](https://github.com/user-attachments/assets/6bc11d9a-41ec-4364-ad7d-9200bde726f0)

**Describe the solution you'd like**
I would like it to ideally be like Bagsync, where it shows the complete list of items and where they're located.

![image](https://github.com/user-attachments/assets/2e49ed76-3826-4a6d-b85c-17578e0389ae)

Bagsync also has an icon for if I currently have it posted on the auction house, which is very useful.

**Describe alternatives you've considered**

**Additional context**

**Comment by plusmouse** [comment]
You can increase the number of characters shown in the tooltip in the settings

**Comment by wheatbread** [comment]
Oh, that's great, thank you!  I missed that.  

I hope you might consider also the location info (specifically indicating bank/ bags/ auction house/ mail/ warband bank/ guild bank).

**Comment by plusmouse** [comment]
It does indicate bank/bags/ah/mail/warband/etc. in the tooltip (as shown in the screenshot on the CF or Wago pages)
