### ISSUE TITLE
Feature Request: Track/calculating currency on alts after transfering

### ISSUE THREAD

**Issue by Breakerzeus** [Baganator/Syndicator#22]
**Is your feature request related to a problem? Please describe.**
Since warband currency can be transferred between warband, it would be nice to have syndicate to automatically track when currency is transferred to the current character and recalculate the amount for the alts.
there is a chat event that mentions the sender, receiver, the currency and the amount. so it will be very possible to track that I guess.

**Describe the solution you'd like**
Automatically track the currency transfers between characters and recalculate the amount left without logging in to these characters.

**Describe alternatives you've considered**
log into characters after transferring currency to let the addon check the current amount of the currency on the specific character.

**Additional context**
Chat event:
![grafik](https://github.com/user-attachments/assets/fc43fdd5-e111-4a3b-9457-39989ea2235a)

**Comment by plusmouse** [comment]
This feature is now in the latest alpha
