### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Gilverion** [Baganator/Syndicator#24]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I am getting a lua error, while hovering  through my items in the inventory.

## Steps to Reproduce

hovering

## Loaded Addons

Baganator, Bugsack, Bugrabber

## Back Trace (LUA Error Output)
27x Syndicator/Tracking/ItemSummaries.lua:321: attempt to index field '?' (a nil value)
[string "@Syndicator/Tracking/ItemSummaries.lua"]:321: in function `GetTooltipInfo'
[string "@Syndicator/Tracking/Tooltips.lua"]:63: in function `AddItemLines'
[string "@Syndicator/Tracking/Main.lua"]:6: in function <Syndicator/Tracking/Main.lua:5>
[string "@Syndicator/Tracking/Main.lua"]:134: in function <Syndicator/Tracking/Main.lua:107>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1532: in function `OnUpdate'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1491: in function `OnEnter'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1487: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1486>
[string "=[C]"]: ?

Locals:
self = Frame {
 SV = <table> {
 }
}
key = "item:103678"
sameConnectedRealm = true
sameFaction = false
realms = <table> {
 Blackhand = true
 Mal'Ganis = true
 Echsenkessel = true
 Taerar = true
}
result = <table> {
 characters = <table> {
 }
 guilds = <table> {
 }
 warband = <table> {
 }
}
currentFaction = "Horde"
(for state) = <table> {
 Blackhand = true
 Mal'Ganis = true
 Echsenkessel = true
 Taerar = true
}
(for control) = "Blackhand"
r = "Blackhand"
charactersByRealm = <table> {
 Gilverion = <table> {
 }
 Gilverin = <table> {
 }
}
guildsByRealm = <table> {
 Voll keine Community = <table> {
 }
}
(for state) = <table> {
 Voll keine Community = <table> {
 }
}
(for control) = "Voll keine Community"
guild = "Voll keine Community"
summary = <table> {
 item:80587 = <table> {
 }
 item:192838 = <table> {
 }
 item:194969 = <table> {
 }
 item:191384 = <table> {
 }
 battlepet:2798 = <table> {
 }
 item:192858 = <table> {
 }
 item:111557 = <table> {
 }
 item:197754 = <table> {
 }
 item:191388 = <table> {
 }
 item:83078 = <table> {
 }
 item:192842 = <table> {
 }
 battlepet:2838 = <table> {
 }
 item:199976 = <table> {
 }
 item:197747 = <table> {
 }
 item:197741 = <table> {
 }
 item:194690 = <table> {
 }
 item:34736 = <table> {
 }
 item:192862 = <table> {
 }
 item:191387 = <table> {
 }
 item:71636 = <table> {
 }
 item:193053 = <table> {
 }
 item:191365 = <table> {
 }
 battlepet:1320 = <table> {
 }
 item:191379 = <table> {
 }
 item:153597 = <table> {
 }
 item:197779 = <table> {
 }
 item:169475 = <table> {
 }
 item:192841 = <table> {
 }
 item:43386 = <table> {
 }
 battlepet:2842 = <table> {
 }
 item:210248 = <table> {
 }
 item:192977 = <table> {
 }
 battlepet:2909 = <table> {
 }
 battlepet:3524 = <table> {
 }
 item:198082 = <table> {
 }
 battlepet:3044 = <table> {
 }
 item:201734 = <table> {
 }
 item:197791 = <table> {
 }
 item:109133 = <table> {
 }
 item:192870 = <table> {
 }
 battlepet:1961 = <table> {
 }
 item:197789 = <table> {
 }
 item:201400 = <table> {
 }
 item:192856 = <table> {
 }
 battlepet:3013 = <table> {
 }
 item:12811 = <table> {
 }
 item:192853 = <table> {
 }
 item:192857 = <table> {
 }
 item:192848 = <table> {
 }
 item:199969 = <table> {
 }
 item:197775 = <table> {
 }
 item:197742 = <table> {
 }
 battlepet:3110 = <table> {
 }
 item:193360 = <table> {
 }
 battlepet:1960 = <table> {
 }
 item:197774 = <table> {
 }
 item:43394 = <table> {
 }
 item:192846 = <table> {
 }
 item:71637 = <table> {
 }
 battlepet:2925 = <table> {
 }
 battlepet:2916 = <table> {
 }
 battlepet:3130 = <table> {
 }
 battlepet:3039 = <table> {
 }
 item:192859 = <table> {
 }
 item:124117 = <table> {
 }
 item:191397 = <table> {
 }
 item:71715 = <table> {
 }
 battlepet:2796 = <table> {
 }
 item:192855 = <table> {
 }
 item:197781 = <table> {
 }
 battlepet:3026 = <table> {
 }
 item:197788 = <table> {
 }
 item:192913 = <table> {
 }
 item:194967 = <table> {
 }
 item:197744 = <table> {
 }
 item:194968 = <table> {
 }
 item:191336 = <table> {
 }
 item:191364 = <table> {
 }
 item:197748 = <table> {
 }
 item:201405 = <table> {
 }
 item:194730 = <table> {
 }
 item:191386 = <table> {
 }
 item:159825 = <table> {
 }
 battlepet:2087 = <table> {
 }
 item:191323 = <table> {
 }
 item:192968 = <table> {
 }
 item:192861 = <table> {
 }
 item:192847 = <table> {
 }
 item:192843 = <table> {
 }
 item:192974 = <table> {
 }
 item:147420 = <table> {
 }
 battlepet:2836 = <table> {
 }
 item:191330 = <table> {
 }
 item:191331 = <table> {
 }
 item:194483 = <table> {
 }
 item:191396 = <table> {
 }
 item:191393 = <table> {
 }
 item:197746 = <table> {
 }
 item:192844 = <table> {
 }
 item:197756 = <table> {
 }
 item:192840 = <table> {
 }
 item:194966 = <table> {
 }
 item:192867 = <table> {
 }
 item:191304 = <table> {
 }
 item:197743 = <table> {
 }
 item:198910 = <table> {
 }
 battlepet:2797 = <table> {
 }
 item:199967 = <table> {
 }
 item:201403 = <table> {
 }
 item:191378 = <table> {
 }
}
byKey = nil
(*temporary) = nil
(*temporary) = "Voll keine Community-Blackhand"
(*temporary) = "-"
(*temporary) = "Blackhand"
(*temporary) = <table> {
}
(*temporary) = "attempt to index field '?' (a nil va

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Have you deleted a guild directly from your saved variables file?

**Comment by Gilverion** [comment]
nope

**Comment by plusmouse** [comment]
For now just open a character in the Voll keine Community guild and the problem should resolve itself

**Comment by Gilverion** [comment]
I tried with 4 chars from the guild and its still showing the lua error

**Comment by plusmouse** [comment]
Did you get any other errors while doing that?

**Comment by Gilverion** [comment]
no only this one,  i tried hovering over items in my bank and guild bank,  it seems to be the onEnter-event. If I leave the mouse on an item the number in the first line rises in bugsack.

**Comment by Gilverion** [comment]
73x Syndicator/Tracking/ItemSummaries.lua:321: attempt to index field '?' (a nil value)
[string "@Syndicator/Tracking/ItemSummaries.lua"]:321: in function `GetTooltipInfo'
[string "@Syndicator/Tracking/Tooltips.lua"]:63: in function `AddItemLines'
[string "@Syndicator/Tracking/Main.lua"]:6: in function <Syndicator/Tracking/Main.lua:5>
[string "@Syndicator/Tracking/Main.lua"]:134: in function <Syndicator/Tracking/Main.lua:107>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1532: in function `OnUpdate'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1491: in function `OnEnter'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1487: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1486>
[string "=[C]"]: ?

Locals:
self = Frame {
 SV = <table> {
 }
}
key = "item:202046"
sameConnectedRealm = true
sameFaction = false
realms = <table> {
 Blackhand = true
 Mal'Ganis = true
 Echsenkessel = true
 Taerar = true
}
result = <table> {
 characters = <table> {
 }
 guilds = <table> {
 }
 warband = <table> {
 }
}
currentFaction = "Horde"
(for state) = <table> {
 Blackhand = true
 Mal'Ganis = true
 Echsenkessel = true
 Taerar = true
}
(for control) = "Blackhand"
r = "Blackhand"
charactersByRealm = <table> {
 Gilverion = <table> {
 }
 Gilverius = <table> {
 }
 Gilverin = <table> {
 }
 Gilveriax = <table> {
 }
 Giljaeden = <table> {
 }
}
guildsByRealm = <table> {
 Voll keine Community = <table> {
 }
}
(for state) = <table> {
 Voll keine Community = <table> {
 }
}
(for control) = "Voll keine Community"
guild = "Voll keine Community"
summary = <table> {
 item:80587 = <table> {
 }
 item:192838 = <table> {
 }
 item:194969 = <table> {
 }
 item:191384 = <table> {
 }
 battlepet:2798 = <table> {
 }
 item:192858 = <table> {
 }
 item:111557 = <table> {
 }
 item:197754 = <table> {
 }
 item:191388 = <table> {
 }
 item:83078 = <table> {
 }
 item:192842 = <table> {
 }
 battlepet:2838 = <table> {
 }
 item:199976 = <table> {
 }
 item:197747 = <table> {
 }
 item:197741 = <table> {
 }
 item:194690 = <table> {
 }
 item:34736 = <table> {
 }
 item:192862 = <table> {
 }
 item:191387 = <table> {
 }
 item:71636 = <table> {
 }
 item:193053 = <table> {
 }
 item:191365 = <table> {
 }
 battlepet:1320 = <table> {
 }
 item:191379 = <table> {
 }
 item:153597 = <table> {
 }
 item:197779 = <table> {
 }
 item:169475 = <table> {
 }
 item:192841 = <table> {
 }
 item:43386 = <table> {
 }
 battlepet:2842 = <table> {
 }
 item:191378 = <table> {
 }
 item:192977 = <table> {
 }
 battlepet:2909 = <table> {
 }
 battlepet:3524 = <table> {
 }
 item:198082 = <table> {
 }
 item:199967 = <table> {
 }
 item:201734 = <table> {
 }
 item:197791 = <table> {
 }
 item:109133 = <table> {
 }
 item:192870 = <table> {
 }
 battlepet:2797 = <table> {
 }
 item:197789 = <table> {
 }
 item:201400 = <table> {
 }
 item:192856 = <table> {
 }
 item:197743 = <table> {
 }
 item:197742 = <table> {
 }
 item:192853 = <table> {
 }
 item:192857 = <table> {
 }
 item:192848 = <table> {
 }
 item:199969 = <table> {
 }
 item:197775 = <table> {
 }
 item:12811 = <table> {
 }
 battlepet:3110 = <table> {
 }
 item:192867 = <table> {
 }
 item:194966 = <table> {
 }
 item:192840 = <table> {
 }
 item:197756 = <table> {
 }
 item:192846 = <table> {
 }
 item:71637 = <table> {
 }
 battlepet:2925 = <table> {
 }
 battlepet:2916 = <table> {
 }
 battlepet:3130 = <table> {
 }
 item:197746 = <table> {
 }
 item:192859 = <table> {
 }
 item:191393 = <table> {
 }
 battlepet:3039 = <table> {
 }
 item:71715 = <table> {
 }
 item:191396 = <table> {
 }
 item:192855 = <table> {
 }
 item:197781 = <table> {
 }
 battlepet:3026 = <table> {
 }
 item:191331 = <table> {
 }
 item:192913 = <table> {
 }
 battlepet:2836 = <table> {
 }
 item:197744 = <table> {
 }
 item:194968 = <table> {
 }
 item:191336 = <table> {
 }
 item:191364 = <table> {
 }
 item:197748 = <table> {
 }
 item:201405 = <table> {
 }
 item:194730 = <table> {
 }
 item:192861 = <table> {
 }
 item:159825 = <table> {
 }
 battlepet:2087 = <table> {
 }
 item:192847 = <table> {
 }
 item:192968 = <table> {
 }
 item:191386 = <table> {
 }
 item:191323 = <table> {
 }
 item:192843 = <table> {
 }
 item:192974 = <table> {
 }
 item:147420 = <table> {
 }
 item:194967 = <table> {
 }
 item:191330 = <table> {
 }
 item:197788 = <table> {
 }
 item:194483 = <table> {
 }
 battlepet:2796 = <table> {
 }
 item:124117 = <table> {
 }
 item:191397 = <table> {
 }
 item:192844 = <table> {
 }
 item:43394 = <table> {
 }
 item:197774 = <table> {
 }
 battlepet:1960 = <table> {
 }
 item:193360 = <table> {
 }
 item:191304 = <table> {
 }
 battlepet:3013 = <table> {
 }
 item:198910 = <table> {
 }
 battlepet:1961 = <table> {
 }
 battlepet:3044 = <table> {
 }
 item:201403 = <table> {
 }
 item:210248 = <table> {
 }
}
byKey = nil
(*temporary) = nil
(*temporary) = "Voll keine Community-Blackhand"
(*temporary) = "-"
(*temporary) = "Blackhand"
(

**Comment by Gilverion** [comment]
i just found  out creating a fresh WTF-Folder solves the problem.
