### ISSUE TITLE
Login error: Blizzard_ObjectAPI\Classic\Item.lua:320 table index is nil (Syndicator\Tracking\BagCache.lua:353)

### ISSUE THREAD

**Issue by Luckyone961** [Baganator/Syndicator#25]
## Brief Description of Bug

Error on login, likely related to Syndicator, as it doesn't pop up without Syndicator enabled.

## Steps to Reproduce

Just logged into the game
Build: 1.15.3.55917
Server: Seasonal

## Loaded Addons

Baganator (v408-classic)
Baganator ElvUI Skin (v7)
Syndicator (v93-classic)

## Back Trace (LUA Error Output)

```Lua
2x Blizzard_ObjectAPI/Classic/Item.lua:320: table index is nil
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:320: in function `GetOrCreateCallbacks'
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:272: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Classic/Item.lua"]:238: in function `ContinueOnItemLoad'
[string "@Syndicator/Tracking/BagCache.lua"]:353: in function `DoSlot'
[string "@Syndicator/Tracking/BagCache.lua"]:374: in function <Syndicator/Tracking/BagCache.lua:292>

Locals:
self = Frame {
 0 = <userdata>
 AddCancelableCallback = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:277
 GetOrCreateCallbacks = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:316
 FireCallbacks = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:292
 callbacks = <table> {}
 GetCallbacks = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:312
 ClearCallbacks = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:308
 AddCallback = <function> defined @Blizzard_ObjectAPI/Classic/Item.lua:271
}
itemID = nil
callbacks = <table> {}
(*temporary) = <table> {}
(*temporary) = "table index is nil"
```

**Comment by Luckyone961** [comment]
After further investigation I'm guessing its because it looks like they broke the [Cozy Sleeping Bag](https://www.wowhead.com/classic/item=211527/cozy-sleeping-bag) item, which cannot retrieve any information on mouseover and also shows a dead, red, questionmark icon.

Baganator sorting will also break if you have this item in your bags or bank.

**Comment by plusmouse** [comment]
Do you know if the item was broken intentionally?

**Comment by Luckyone961** [comment]
Pretty sure they hotfixed it, the item tooltip is back and the error no longer pops on login

**Comment by plusmouse** [comment]
Awesome. Hopefully this won't crop up again.
