### ISSUE TITLE
Lua error thrown on mailbox item deletion

### ISSUE THREAD

**Issue by Saaappi** [Baganator/Syndicator#29]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I tried to delete an item (a leftover letter) from a mailbox item.

## Steps to Reproduce

It was either while Open All was running that I tried to delete the letter, or after Open All had completed and I tried to delete the letter.

It only failed once, and I was able to delete it the second time. Could have been a fluke. I hope the trace below helps you identify the issue.

## Loaded Addons

- AddonFactory
- AllTheThings
- Baganator/Syndicator (obviously)
- BtWLoadouts
- BugGrabber/BugSack
- Delete Hearthstone
- Details!
- ExtraQuestButton
- Grail
- HelpMePlay
- MinimapButtonBag-Reborn
- OPie
- Plater
- TomTom
- Wholly
- WoWthing Collector
- Zygor

## Back Trace (LUA Error Output)

```
1x Syndicator/Tracking/MailCache.lua:88: attempt to index local 'recipient' (a nil value)
[string "@Syndicator/Tracking/MailCache.lua"]:88: in function <Syndicator/Tracking/MailCache.lua:85>
[string "=[C]"]: in function `ReturnInboxItem'
[string "@Blizzard_MailFrame/MailFrame.lua"]:871: in function <Blizzard_MailFrame/MailFrame.lua:859>

Locals:
mailIndex = 3
recipient = nil
(*temporary) = 3
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'recipient' (a nil value)"
self = Frame {
 currentCharacter = "Artyfischel-AeriePeak"
}
```

**Comment by plusmouse** [comment]
Added a fix to prevent this error happening again.
