### ISSUE TITLE
Adjust the amount of currency on the sender when transferring currency to your logged in character

### ISSUE THREAD

**Issue by Myrhial** [Baganator/Syndicator#31]
**Is your feature request related to a problem? Please describe.**
With currency transfer now being a thing, I have centralised some currency onto one character for easier spending. However Syndicator does not correct the currency total of the other characters, unless you log those in. This is misleading because it gives the impression I have more currency on my account in total than I actually do.

**Describe the solution you'd like**
When I transfer a currency from Alt B to main character A, Syndicator subtracts this from the currency total of Alt B. Hopefully there is an event for this that you can hook into which contains the sender, the receiver, the type and the amount. If this is not possible, some sort of way to mark that totals may no longer be accurate would be good enough.

**Describe alternatives you've considered**
I could log Alt B in and then the amount is updated, but this can get tedious if you need to do it for a lot of alts.

**Comment by plusmouse** [comment]
Fixed in the latest alpha
