### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by BlueNightSky** [Baganator/Syndicator#32]
## Back Trace (LUA Error Output)
1x Syndicator/Search/Initialize.lua:2: attempt to call field 'InitializeSearchEngine' (a nil value)
[string "@Syndicator/Search/Initialize.lua"]:2: in function `Initialize'
[string "@Syndicator/Core/Main.lua"]:12: in function `cb'
[string "@Syndicator/Core/Utilities.lua"]:12: in function <Syndicator/Core/Utilities.lua:9>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'InitializeSearchEngine' (a nil value)"

**Comment by plusmouse** [comment]
Is this on classic, retail, classic era?

**Comment by BlueNightSky** [comment]
Retail

**Comment by plusmouse** [comment]
What versions of Syndicator and Baganator?

**Comment by BlueNightSky** [comment]
After I upgrade to the latest version, there is no error anymore. Thank you!
