### ISSUE TITLE
Transferring currencies doesnt update source characters total

### ISSUE THREAD

**Issue by ESpmdark** [Baganator/Syndicator#36]
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

104

### What isn't working? What was supposed to happen?

Not sure when this stopped working, as it was ok previously. However, any warbound currency I attempt to transfer with now, doesnt update the source characters total.
I tried transferring all available, aswell as partly. Same result.

Will only update after I log onto that character for a direct refresh

### Are you experiencing any lua errors

No errors.

**Comment by plusmouse** [comment]
Should be working in the latest alpha now.
