### ISSUE TITLE
Transfer tracking when the transfer has a tax

### ISSUE THREAD

**Issue by ESpmdark** [Baganator/Syndicator#42]
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

107

### What isn't working? What was supposed to happen?

This will be somewhat less than helpful bug-report. As I did not submit the report while it was fresh in my mind:

A couple of days ago (I think I was on version 107 then), I did a currency transfer that had a % loss.
Example values (since I dont remember the spesifics):
10k from source
2k lost
8k to new character

Syndicator tracked only 8k removed from the source character, where it should have retracted 10k from the source currency-count.

I dont have more of the currency to test if this is fixed in newer versions, but I'd rather submit a heads up -report for you incase you werent aware of this.

**Comment by plusmouse** [comment]
What currency has a transfer tax?

**Comment by zeenk** [comment]
https://www.wowhead.com/news/transfering-currencies-within-your-warband-available-currencies-transfer-rates-339048

dno if this list is updated anymore though, anima is not transferable anymore but it's on the list

**Comment by plusmouse** [comment]
Thanks for the detailed report. I've added taking the transfer tax into account into the latest alpha now :)
