### ISSUE TITLE
Tons of LUA errors when opening the auction house

### ISSUE THREAD

**Issue by Seanj527** [Baganator/Syndicator#47]
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

114

### What isn't working? What was supposed to happen?

I'm getting constant LUA errors when opening the AH

Here is a paste of it: 

Message: ...ce/AddOns/Syndicator/Tracking/AuctionCacheRetail.lua:270: attempt to index field 'purchasedCommodity' (a nil value)
Time: Sun Sep  1 21:09:55 2024
Count: 592
Stack: ...ce/AddOns/Syndicator/Tracking/AuctionCacheRetail.lua:270: attempt to index field 'purchasedCommodity' (a nil value)
[string "@Interface/AddOns/Syndicator/Tracking/AuctionCacheRetail.lua"]:270: in function <...ce/AddOns/Syndicator/Tracking/AuctionCacheRetail.lua:269>
[string "@Interface/AddOns/Syndicator/Tracking/AuctionCacheRetail.lua"]:286: in function `callback'
[string "@Interface/AddOns/Syndicator/Core/Utilities.lua"]:74: in function <Interface/AddOns/Syndicator/Core/Utilities.lua:71>
[string "=[C]"]: ?
[string "=[C]"]: in function `RequestLoadItemDataByID'
[string "@Interface/AddOns/Syndicator/Core/Utilities.lua"]:83: in function <Interface/AddOns/Syndicator/Core/Utilities.lua:79>

Locals: (*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to index field 'purchasedCommodity' (a nil value)"
self = Frame {
 currentCharacter = "Wôlfie-Illidan"
 purchasedItem = <table> {
 }
}
itemID = 222520
itemCount = 2

### Are you experiencing any lua errors

Yes, see above section.

**Comment by plusmouse** [comment]
These happen when you open the AH, or after you've done something? Do you have any AH addons installed?

**Comment by Seanj527** [comment]
I have auctionator installed and turned on. I have TSM too, but it is disabled on that character and shouldn't be causing issues I believe.

**Comment by plusmouse** [comment]
Found the issue and added a fix. Thanks for the bug report.
