### ISSUE TITLE
why do i need this ? i only want baganator

### ISSUE THREAD

**Issue by Fleymour** [Baganator/Syndicator#48]
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

119

### What isn't working? What was supposed to happen?

why do i need this ? i only want baganator - when this is addon is mandatory why it isnt implemented inside baganator and not a seperated addon ?

**Comment by zeenk** [comment]
Syndicator gets installed automatically when you install Baganator from the Curse app, but if you installed it manually it won't do that, and it's required as it stores all the character data

It's also separated so people who don't want a full bag ui addon can still just use Syndicator for the inventory data in tooltips and use the account wide searching `/syns` command for items

**Comment by Fleymour** [comment]
yeah i have TSM for character bag / bank item data... thats why i dont need that on top ;-/

**Comment by Fleymour** [comment]
> Syndicator gets installed automatically when you install Baganator from the Curse app, but if you installed it manually it won't do that, and it's required as it stores all the character data

and what happens when i update the addon with curse later? seems weird that curseforge automatically suggest an extra addon

**Comment by plusmouse** [comment]
Syndicator handles processing new bag data for the Baganator addon to use in displaying the current bags, so is an unavoidable dependency.

**Comment by plusmouse** [comment]
You can disable the tooltip information in the Syndicator settings (untick the top checkbox)
