### ISSUE TITLE
Missing update when leaving a guild

### ISSUE THREAD

**Issue by ESpmdark** [Baganator/Syndicator#49]
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

121

### What isn't working? What was supposed to happen?

Syndicator doesnt update its character data on the field "guild" when you leave a guild.

My character that I intended to be guildless, is still tied to the guild in the stored config, thus I can check the bank on the character.

Not sure if listening to guild roster -events is such a good idea as a solution. Perhaps it would be less invasive if a cleanup-function for this was tied to initialization instead?
But the choice of solution is yours ofcourse, just thought I'd leave my suggestion.

### Are you experiencing any lua errors

No errors

**Comment by plusmouse** [comment]
It should cleanup when you reload.

**Comment by ESpmdark** [comment]
Thats what I assumed, so I tried reloading and even fully logging out/in aswell. But it didnt update.
So I checked the saved file, and saw that my character still had its old guildname listed as his current guild in the files.

So I'm not sure whats going on. but added context:

I have other characters that are still in the guild.
So expected behaviour isnt to remove guild data in this case. 

Just the characters listing of what guild he is in (as he's guildless now).

What I would assume the following behaviour for cleanup:

- Remove any reference to any guild if you're guildless
- If none of your characters are in guild "guildname", remove all saved data for "guildname" all together.

From what I can see currently, none of these 2 behaviours would be executed, since character data isnt being updated for the guild-field.

**Comment by plusmouse** [comment]
Found the issue. I broke it in the last rework 😂

**Comment by plusmouse** [comment]
Try this next alpha (out shortly)

**Comment by ESpmdark** [comment]
Tested, character is cleaned up

Also did a quick test with the other thing I mentioned (although it probably should be its own bug report, not piggybacking on this one).

- Left a guild that I only had one character in (old unused guild bank character).
The guild itself is still stored inn saved config file. Eventhough I now dont have any character in the guild.

Reloaded, relogged etc. Still within the saved data.
Now ofcourse, this is very minor. But its more of a heads up in regards to keeping unused data within the saved variables file.

**Comment by plusmouse** [comment]
This can be safely removed with `/syn removeguild GuildName-RealmNameNoSpaces`
