### ISSUE TITLE
Question: correct "Search" for an "all caches" category

### ISSUE THREAD

**Issue by Jahfry** [Baganator/Syndicator#53]
### What version(s) of WoW are you using?

Retail

### What problem are you experiencing that led to you asking for this feature?

First off, if there's a discord or forum for asking usage questions ... shuffle me off to there. Don't mean to fill up Issues with non-Issues. 

...

**Question:** I have a category for "Caches" with the following Search:

`Cache | Purse | Pouch | Trove | !gear & Chest | Capital | Bag | Valorstone`

Specific issue I'm having is "Chest" matches gear locations and enchant locations. But it leads to a general issue for anything else that matches one of the other names (like "Bag" would also be a lot of containers). 

*Do caches (like drop from weekly TWW quests, etc, that give various rewards) fall into the Container class? Or some other class?* ***If not ... I guess this is a request afterall for a "Cache reward" selectable class :)***

...

Otherwise I can probably do a bunch of combinations to get things to categorize properly but the search is going to become really big. ***In which case a multi-line box for searches is another possible enhancement.***

...

**Final related question:** can we group with () like:

*other stuff* | (!gear & !enhancement & chest) | *other stuff*

*If not, grouping would be a welcome addition for a more regex experience. *

...

Thanks as always for the 'nators :)

### What solution would you like?

(see first info)

**Comment by zeenk** [comment]
The discord is: https://discord.gg/TtSN6DxSky

To you question, to avoid wrong categories having mismatches you should put # in front of the search like `#container` that makes it so it only searches for keyword items that matches that specific keyword, if you don't use the # it will then scan the whole name so if any item has container in it, that item will also be included in the category.
And yes you can do search combos like `#gear&#boe` or `#gear&(#boe|#wue)` 

Helpful tip: use the command `/bgr keywords` that will add a list of keywords on the item's tooltips, very useful when making categories to know what search combos to use.
There is also a ? next to the search bar in your bags that you can check out that includes all the keywords available you can use.

**Comment by Jahfry** [comment]
I received a response in email from zENK but haven't seen it appear here. 

> The discord is: https://discord.gg/TtSN6DxSky
> 
> To you question, to avoid wrong categories having mismatches you should put # in front of the search like #container that makes it so it only searches for keyword items that matches that specific keyword, if you don't use the # it will then scan the whole name so if any item has container in it, that item will also be included in the category.
> 
> And yes you can do search combos like #gear&#boe or #gear&(#boe|#wue)
> 
> Helpful tip: use the command /bgr keywords that will add a list of keywords on the item's tooltips, very useful when making categories to know what search combos to use.

> There is also a ? next to the search bar in your bags that you can check out that includes all the keywords available you can use.

Thank you. This solved my immediate needs and am closing this. I may file a new request for a "caches" line. For now this is my TWW search for a "Caches" category. It unfortunately also matches containers (from 'Bag') but still useful. 

`! gear & (Cache | Purse | Pouch | Trove | Chest | Capital | Bag | Valorstone | Gratuity)`

**Comment by zeenk** [comment]
I got confused for a second that's why I removed it, thought it was a Syndicator only post and I gave some tips for Baganator which didn't really make sense if you were not using Syndicator but after I deleted it and re-read the post I realized it was correctly posted lol but glad you somewhat got your problem sorted.

You could probably just use `#open` for this category, that will highlight all items that has this <Right click to open> text under them, I think most of those items that you are looking for has that?

**Comment by Jahfry** [comment]
#open ... I'll give that a look. If that's what it does, ayup, that would mean the feature I was hoping for is there. Thanks again :)
