### ISSUE TITLE
Tooltips not showing on consumable macros

### ISSUE THREAD

**Issue by Petrol30** [Baganator/Syndicator#57]
### What version(s) of WoW are you using?

Retail

### What version of Syndicator?

135

### What isn't working? What was supposed to happen?

When mouse overing a macro on my action bar for Tempered Potion (and other consumables), the tooltips for how many of the item is in my bags / bank / etc is not showing.

**Comment by plusmouse** [comment]
This is an artifact of the Blizzard APIs limiting what can detected about an item in the tooltip of a macro. This isn't fixable.

**Comment by Petrol30** [comment]
Hey there,
Thanks for your quick reply.
I won't pretend to understand how these things work, but the addon Item Count is able to do this.
(Not sure if there was some trickery involved or just done in a different way).

![image](https://github.com/user-attachments/assets/20c4ec50-aa36-4eb1-86b2-b62f954cd5b9)
