### ISSUE TITLE
Opening Guild Bank when not in guild throws LUA error

### ISSUE THREAD

**Issue by Cerrendel** [Baganator/Syndicator#7]
## Brief Description of Bug
Opening Guild Bank when not in guild throws LUA error.
I have only tested this on Cataclysm. It may occur in other classic versions.

## Steps to Reproduce
1. Log in with an unguilded character.
2. Open the guild bank 

## Back Trace (LUA Error Output)
Message: Interface/AddOns/Syndicator/Tracking/GuildCache.lua:166: attempt to index local 'data' (a nil value)
Time: Sun Apr 28 15:59:09 2024
Count: 1
Stack: Interface/AddOns/Syndicator/Tracking/GuildCache.lua:166: attempt to index local 'data' (a nil value)
[string "@Interface/AddOns/Syndicator/Tracking/GuildCache.lua"]:166: in function `ExamineGeneralTabInfo'
[string "@Interface/AddOns/Syndicator/Tracking/GuildCache.lua"]:87: in function <Interface/AddOns/Syndicator/Tracking/GuildCache.lua:82>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: self = Frame {
 0 = <userdata>
 OnLoad = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:61
 ExamineAllBankTabs = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:199
 OnEvent = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:82
 StartFullBankScan = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:114
 lastTabPickups = <table> {
 }
 ExamineBankTab = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:223
 ExamineGeneralTabInfo = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:161
 OnUpdate = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:131
 ProcessTransfers = <function> defined @Interface/AddOns/Syndicator/Tracking/GuildCache.lua:136
}
start = 1061973506.120900
data = nil
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"

**Comment by plusmouse** [comment]
Fixed in version 25 (available shortly)
