### ISSUE TITLE
lua errors (lots of them)

### ISSUE THREAD

**Issue by fireymerlin** [Baganator/Syndicator#8]
2x Syndicator/Tracking/Tooltips.lua:32: attempt to index local 'summaries' (a nil value)
[string "@Syndicator/Tracking/Tooltips.lua"]:32: in function `AddItemLines'
[string "@Syndicator/Tracking/Main.lua"]:6: in function <Syndicator/Tracking/Main.lua:5>
[string "@Syndicator/Tracking/Main.lua"]:147: in function <Syndicator/Tracking/Main.lua:141>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:95: in function <.../Core/
Please include as much of the following information as possible to help me fix the bug:

Started on May 13, 2024 after updating.

**Comment by plusmouse** [comment]
Can you post the first lua error?

**Comment by plusmouse** [comment]
Replicated and fixed the lua errors. Fix available as version 32,

[Syndicator-32.zip](https://github.com/Baganator/Syndicator/files/15301645/Syndicator-32.zip)

**Comment by fireymerlin** [comment]
Thanks for the fast response.
