### ISSUE TITLE
lua errors:  lots of them.

### ISSUE THREAD

**Issue by fireymerlin** [Baganator/Syndicator#9]
14x Syndicator/Tracking/ItemSummaries.lua:276: attempt to index field '?' (a nil value)
[string "@Syndicator/Tracking/ItemSummaries.lua"]:276: in function `GetTooltipInfo'
[string "@Syndicator/Tracking/Tooltips.lua"]:32: in function `AddItemLines'
[string "@Syndicator/Tracking/Main.lua"]:6: in function <Syndicator/Tracking/Main.lua:5>
[string "@Syndicator/Tracking/Main.lua"]:147: in function <Syndicator/Tracking/Main.lua:141>

I'm using version 37.2 in hardcore classic.

**Comment by plusmouse** [comment]
Did you delete a character recently?

**Comment by fireymerlin** [comment]
I deleted a character.
I did not use the slash commands.  I removed from the savedvaraiable file(s).  I didn't know there was a slash command.

**Comment by plusmouse** [comment]
You'll need to find the other instance of the character's name in the saved variables and remove that too.

I didn't transfer the character/guild delete or hide commands documentation to the Syndicator page when splitting the addons up a while back, so have added it now.
